#-*- coding:utf-8 -*-
age = [3, 2, 30, 1, 16, 18, 19, 20, 22, 25]
name = ['lizi', 'liudehua', 'linjunjie', 'zhoujielun', 'zhangsan', 'bigmom', 'kaiduo', 'luffe']
print(age)
print(sorted(age))
print(age)
age.sort()
print(age)
age.append(33)
print(age)
age.insert(2, 65)
print(age)
age.pop()
print(age)
_del = age.pop()
print(_del)
print(age)
del age[0:2]
print(age)
age.remove(22)
print(age)
print(sorted(name))
print(name)
name.sort()
print(name)
name.sort(reverse=False)
print(age)
name.reverse()
print(name)